name: Feature Request
description: Suggest a new feature or improvement for the WyvenCraft Minecraft server
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below to help us understand your request.
  
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of what you want to happen.
      placeholder: Briefly describe the feature...
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe how this feature would work...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other ways this could be implemented...
    validations:
      required: false
  
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature improve the server or player experience?
      placeholder: This would help by...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false
